---
# see http://molecule.readthedocs.io/en/stable-1.9/usage.html
language: python

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - vagrant

rvm:
  - 2.2.0

install:
  - pip install -r requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
