---
- name: install git packages
  package:
    name: "{{ git_packages }}"
    state: "{{ git_packages_state }}"
  become: yes
  tags:
    - git

- name: Execute lfs auto install command
  shell: |
    curl -s {{ git_lfs_install_url }} | bash
  when: git_lfs_install_url is defined
  changed_when: false
  tags:
    - git
    - skip_ansible_lint

- name: Install git-lfs package
  package: |
    name: {{ git_packages_lfs }}
    state: {{ git_packages_state }}
  when: git_packages_lfs is defined
  tags:
    - git

- name: Initialize git-lfs
  shell: git lfs install
  when: git_packages_lfs is defined
  changed_when: false
  tags:
    - git
    - skip_ansible_lint

- name: set up git prompt
  copy:
    dest: "~/{{ git_prompt_path }}"
    src: "{{ git_prompt_template }}"
  no_log: yes
  tags:
    - git

- name: configure git prompt
  lineinfile:
    dest: "~/{{ bash_configuration_file }}"
    line: '[[ -f ~/{{ git_prompt_path }} ]] && source ~/{{ git_prompt_path }}'
    create: yes
  tags:
    - git

- name: set up git completion
  copy:
    dest: "~/{{ git_completion_path }}"
    src: "{{ git_completion_template }}"
  no_log: yes
  tags:
    - git

- name: configure git completion
  lineinfile:
    dest: "~/{{ bash_configuration_file }}"
    line: '[[ -f ~/{{ git_completion_path }} ]] && source ~/{{ git_completion_path }}'
    create: yes
  tags:
    - git
